server:
  port: 9000


eureka:
  instance:
    hostname: 127.0.0.1 # 主机名
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
spring:
  application:
    name: gateway-consumer

# 开启feign对hystrix的支持
feign:
  hystrix:
    enabled: true